jobs:
  - job: Windows
    strategy:
      matrix:
        MSVC_2015:
          MUMBLE_QT: qt5
          MUMBLE_HOST: x86_64-pc-windows-msvc
          MUMBLE_PUBLISH_INSTALLER: 1
        MSVC_2015_NO_PCH:
          MUMBLE_QT: qt5
          MUMBLE_HOST: x86_64-pc-windows-msvc
          MUMBLE_NO_PCH: 1
    steps:
    - script: git submodule --quiet update --init --recursive
      displayName: 'Fetch submodules'
    - powershell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install 7zip.install -y
      displayName: 'Install 7-Zip via Chocolatey'
    - powershell: scripts/azure-pipelines/install-environment.ps1
      displayName: 'Install build environment'
    - powershell: scripts/azure-pipelines/build.ps1
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: WindowsInstaller
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: git submodule --quiet update --init --recursive
      displayName: 'Fetch submodules'
    - script: scripts/azure-pipelines/install-environment_linux.bash
      displayName: 'Install build environment'
    - script: scripts/azure-pipelines/build_linux.bash
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: AppImage
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
    - script: git submodule --quiet update --init --recursive
      displayName: 'Fetch submodules'
    - script: scripts/azure-pipelines/install-environment_macos.bash
      displayName: 'Install build environment'
    - script: scripts/azure-pipelines/build_macos.bash
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: macOS installer
